# Generated by Django 4.0.4 on 2022-05-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suplier',
            new_name='Supplier',
        ),
    ]
